DROP DATEBASE IF EXISTS vue02;
CREATE DATABASE IF NOT EXISTS vue02;
USE vue02;


DROP TABLE IF NOT EXISTS users;

CREATE TABLE IF NOT EXISTS users(
id BIGINT PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(30) NOT NULL UNIQUE,
password VARCHAR(30) NOT NULL,
email VARCHAR(30)
);



